# ============================================================================
# CONFIGURAÇÃO PROMETHEUS
# Monitoramento Inteligente de Clusters - IF-UFG
# ============================================================================

global:
  scrape_interval: 15s
  evaluation_interval: 15s

# ============================================================================
# REGRAS DE ALERTA
# ============================================================================
rule_files:
  - "rules/*.yml"

# ============================================================================
# CONFIGURAÇÕES DE ALERTA
# ============================================================================
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alerting:8000

# ============================================================================
# TARGETS DE SCRAPE
# ============================================================================
scrape_configs:
  # ============================================================================
  # PROMETHEUS (AUTO-MONITORAMENTO)
  # ============================================================================
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # ============================================================================
  # EXPORTADOR MQTT
  # ============================================================================
  - job_name: 'mqtt-exporter'
    static_configs:
      - targets: ['mqtt-exporter:8000']
    scrape_interval: 10s
    metrics_path: '/metrics'

  # ============================================================================
  # NODE EXPORTER (MÉTRICAS DO SISTEMA)
  # ============================================================================
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # ============================================================================
  # CADVISOR (MÉTRICAS DE CONTAINERS)
  # ============================================================================
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s

  # ============================================================================
  # SISTEMA DE ALERTAS
  # ============================================================================
  - job_name: 'alerting-system'
    static_configs:
      - targets: ['alerting:8000']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # ============================================================================
  # GRAFANA (OPCIONAL)
  # ============================================================================
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 60s
    metrics_path: '/metrics'
    scrape_timeout: 10s 